# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Development Journal
email: phillippenny@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  As part of my MA in Creative App Development, I will be keeping this weekly blog
  to increase self-awareness and understanding as I develop my skills.
baseurl: /journal
url: "https://plantio.ruuts.co.uk" # the base hostname & protocol for your site
github_username:  phlillip

# Build settings
markdown: kramdown
